# Generated by Django 4.2.2 on 2023-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
